'use client';

import React, { useState } from 'react';
import { X, CheckCircle2 } from 'lucide-react';
import { useApp } from '@/context/AppContext';
import { CROP_OPTIONS, COLLECTION_CENTRES } from '@/lib/data';

export default function AddBatchModal() {
  const { isAddBatchOpen, setIsAddBatchOpen, addBatch, batches } = useApp();

  const nextBatchNum = batches.length + 1;
  const autoGeneratedId = `AT-${String(nextBatchNum).padStart(3, '0')}`;

  const [formData, setFormData] = useState({
    crop: 'Tomato',
    variety: 'Hybrid F1',
    collectionCentre: COLLECTION_CENTRES[0],
    quantity: '100',
    farmerSupplier: '',
    initialTemperature: '33.5',
    targetTemperature: '24.0',
    notes: '',
  });

  const [isSubmitted, setIsSubmitted] = useState(false);

  if (!isAddBatchOpen) return null;

  const handleSubmit = (e) => {
    e.preventDefault();

    const now = new Date();
    const newBatch = {
      id: autoGeneratedId,
      crop: formData.crop,
      variety: formData.variety || 'Standard Lot',
      collectionCentre: formData.collectionCentre,
      quantity: parseFloat(formData.quantity) || 50,
      arrivalDateTime: now.toISOString(),
      coolingStartTime: now.toISOString(),
      initialTemperature: parseFloat(formData.initialTemperature) || 32.0,
      currentTemperature: parseFloat(formData.initialTemperature) || 32.0,
      targetTemperature: parseFloat(formData.targetTemperature) || 24.0,
      status: 'COOLING',
      coolingDurationMinutes: 0,
      farmerSupplier: formData.farmerSupplier || 'Local Producer Cluster',
      ambientTemperature: 33.0,
      relativeHumidity: 68,
      coolingPotential: 'Favorable',
      waterUsedLiters: null,
      energyUsedKwh: null,
      hasResourceMeters: false,
      isDemo: true,
      notes: formData.notes || 'Batch registered at collection centre intake.',
      decisionReason: 'Cooling initiated. Monitoring initial evaporative temperature response.',
      timeline: [
        { 
          time: now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }), 
          event: 'Batch Arrived & Weighed', 
          status: 'completed', 
          detail: `${formData.quantity} kg registered at ${formData.initialTemperature}°C.` 
        },
        { 
          time: now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }), 
          event: 'Cooling Started', 
          status: 'active', 
          detail: 'Demo cooling rig engaged.' 
        },
        { 
          time: 'Est. +45 min', 
          event: 'Target Completion', 
          status: 'pending', 
          detail: `Target core temperature: ${formData.targetTemperature}°C.` 
        }
      ]
    };

    addBatch(newBatch);
    setIsSubmitted(true);
    setTimeout(() => {
      setIsSubmitted(false);
      setIsAddBatchOpen(false);
    }, 1200);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-[#0D1117]/80 backdrop-blur-sm animate-fade-in">
      <div 
        className="bg-[#21262D] rounded-2xl border border-[#30363D] shadow-2xl w-full max-w-lg overflow-hidden card-transition"
        role="dialog"
        aria-modal="true"
      >
        {/* Modal Header */}
        <div className="px-6 py-4 border-b border-[#30363D] flex items-center justify-between bg-[#161B22]">
          <div>
            <h3 className="text-base font-bold text-[#F0F3F0]">Add Incoming Batch</h3>
            <p className="text-xs text-[#B8C0C7]">Register produce lot for cooling and temperature logging</p>
          </div>
          <button
            onClick={() => setIsAddBatchOpen(false)}
            className="p-1.5 rounded-lg text-[#7D8790] hover:text-[#F0F3F0] hover:bg-[#21262D] btn-transition cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {isSubmitted ? (
          <div className="p-8 text-center flex flex-col items-center justify-center space-y-3">
            <div className="w-12 h-12 rounded-full bg-[#161B22] text-[#39FF14] border border-[#30363D] flex items-center justify-center">
              <CheckCircle2 className="w-6 h-6" />
            </div>
            <h4 className="text-lg font-bold text-[#F0F3F0]">Batch Added Successfully</h4>
            <p className="text-xs text-[#B8C0C7]">
              {autoGeneratedId} ({formData.crop}, {formData.quantity} kg) is now active for monitoring.
            </p>
          </div>
        ) : (
          <form onSubmit={handleSubmit} className="p-6 space-y-4 max-h-[80vh] overflow-y-auto">
            {/* Auto ID & Collection Centre */}
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-[11px] font-semibold uppercase tracking-wider text-[#B8C0C7] mb-1">
                  Batch ID (Auto)
                </label>
                <input
                  type="text"
                  value={autoGeneratedId}
                  disabled
                  className="w-full px-3 py-2 text-xs font-mono font-bold bg-[#161B22] text-[#39FF14] rounded-lg border border-[#30363D] cursor-not-allowed"
                />
              </div>

              <div>
                <label className="block text-[11px] font-semibold uppercase tracking-wider text-[#B8C0C7] mb-1">
                  Collection Centre
                </label>
                <select
                  value={formData.collectionCentre}
                  onChange={(e) => setFormData({ ...formData, collectionCentre: e.target.value })}
                  className="w-full px-3 py-2 text-xs bg-[#161B22] text-[#F0F3F0] rounded-lg border border-[#30363D] focus:border-[#39FF14] focus:outline-none"
                >
                  {COLLECTION_CENTRES.map(c => <option key={c} value={c}>{c}</option>)}
                </select>
              </div>
            </div>

            {/* Crop & Variety */}
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-[11px] font-semibold uppercase tracking-wider text-[#B8C0C7] mb-1">
                  Crop Type
                </label>
                <select
                  value={formData.crop}
                  onChange={(e) => setFormData({ ...formData, crop: e.target.value })}
                  className="w-full px-3 py-2 text-xs bg-[#161B22] text-[#F0F3F0] rounded-lg border border-[#30363D] focus:border-[#39FF14] focus:outline-none"
                >
                  {CROP_OPTIONS.map(c => <option key={c} value={c}>{c}</option>)}
                </select>
              </div>

              <div>
                <label className="block text-[11px] font-semibold uppercase tracking-wider text-[#B8C0C7] mb-1">
                  Variety / Grade
                </label>
                <input
                  type="text"
                  value={formData.variety}
                  onChange={(e) => setFormData({ ...formData, variety: e.target.value })}
                  placeholder="e.g. Arka Rakshak"
                  className="w-full px-3 py-2 text-xs bg-[#161B22] text-[#F0F3F0] placeholder-[#7D8790] rounded-lg border border-[#30363D] focus:border-[#39FF14] focus:outline-none"
                />
              </div>
            </div>

            {/* Quantity & Initial Temperature */}
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-[11px] font-semibold uppercase tracking-wider text-[#B8C0C7] mb-1">
                  Quantity (kg)
                </label>
                <input
                  type="number"
                  required
                  min="10"
                  max="5000"
                  value={formData.quantity}
                  onChange={(e) => setFormData({ ...formData, quantity: e.target.value })}
                  className="w-full px-3 py-2 text-xs bg-[#161B22] text-[#F0F3F0] rounded-lg border border-[#30363D] focus:border-[#39FF14] focus:outline-none"
                />
              </div>

              <div>
                <label className="block text-[11px] font-semibold uppercase tracking-wider text-[#B8C0C7] mb-1">
                  Initial Produce Temp (°C)
                </label>
                <input
                  type="number"
                  step="0.1"
                  required
                  value={formData.initialTemperature}
                  onChange={(e) => setFormData({ ...formData, initialTemperature: e.target.value })}
                  className="w-full px-3 py-2 text-xs bg-[#161B22] text-[#F0F3F0] rounded-lg border border-[#30363D] focus:border-[#39FF14] focus:outline-none"
                />
              </div>
            </div>

            {/* Farmer / Supplier */}
            <div>
              <label className="block text-[11px] font-semibold uppercase tracking-wider text-[#B8C0C7] mb-1">
                Farmer / Supplier Name
              </label>
              <input
                type="text"
                placeholder="e.g. K. Murugan - Tiruvallur Cluster"
                value={formData.farmerSupplier}
                onChange={(e) => setFormData({ ...formData, farmerSupplier: e.target.value })}
                className="w-full px-3 py-2 text-xs bg-[#161B22] text-[#F0F3F0] placeholder-[#7D8790] rounded-lg border border-[#30363D] focus:border-[#39FF14] focus:outline-none"
              />
            </div>

            {/* Batch Notes */}
            <div>
              <label className="block text-[11px] font-semibold uppercase tracking-wider text-[#B8C0C7] mb-1">
                Batch Notes
              </label>
              <textarea
                rows={2}
                placeholder="e.g. Morning harvest, stacked with 50mm airflow gap..."
                value={formData.notes}
                onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
                className="w-full px-3 py-2 text-xs bg-[#161B22] text-[#F0F3F0] placeholder-[#7D8790] rounded-lg border border-[#30363D] focus:border-[#39FF14] focus:outline-none resize-none"
              />
            </div>

            {/* Actions */}
            <div className="pt-4 border-t border-[#30363D] flex items-center justify-end gap-3">
              <button
                type="button"
                onClick={() => setIsAddBatchOpen(false)}
                className="px-4 py-2 text-xs font-semibold text-[#F0F3F0] bg-[#21262D] hover:bg-[#2A3139] rounded-lg border border-[#30363D] btn-transition cursor-pointer"
              >
                Cancel
              </button>
              <button
                type="submit"
                className="px-5 py-2 text-xs font-bold text-[#0D1117] bg-[#39FF14] hover:bg-[#32e612] rounded-lg shadow-sm btn-transition cursor-pointer"
              >
                Save Batch
              </button>
            </div>
          </form>
        )}
      </div>
    </div>
  );
}
